Repository aframevr/aframe, pull requests merged in 2018-08, with the labels that each got.

#3717 add logarithmicDepthBuffer option
  src/components/scene/renderer.js
  src/core/scene/a-scene.js
Labels: needs changes

#3739 update canvas bounds for mouse cursor on renderer resize
  src/components/cursor.js
  src/core/scene/a-scene.js
Labels: needs review

#3741 check geometry is set first in text updateLayout
  src/components/text.js
Labels: needs tests fixed
