Repository aframevr/aframe, pull requests merged in 2018-03, with the labels that each got.

#3413 keyboard-shortcuts adds and removes event listeners in play/pause
  src/components/scene/keyboard-shortcuts.js
Labels: needs changes

#3409 Clone the properties that are object type into oldData so the update …
  src/core/component.js
  tests/components/line.test.js
Labels: needs review

#3438 use optionalTarget for raycaster.intersectObjects to save array (fixes #3437)
  package.json
  src/components/raycaster.js
Labels: needs review

#3439 minor optimizations/best practices to look-controls
  src/components/look-controls.js
  tests/components/look-controls.test.js
Labels: needs review

#3489 simple fix for Gear VR and Oculus Touch controller issues (fixes #3447 and #3483)
  src/utils/index.js
  src/utils/split.js
  src/utils/tracked-controls.js
Labels: needs changes

#3490 remove default components
  src/components/position.js
  src/components/rotation.js
  src/components/scale.js
  src/components/scene/vr-mode-ui.js
  src/core/a-entity.js
  src/core/scene/a-scene.js
  tests/core/a-entity.test.js
  tests/core/component.test.js
Labels: needs review

#3498 [docs] Update camera position/offset documentation.
  docs/components/camera.md
  docs/components/look-controls.md
  docs/components/wasd-controls.md
  docs/primitives/a-camera.md
  src/extras/primitives/primitives/a-camera.js
Labels: documentation
