Repository aframevr/aframe, pull requests merged in 2019-04, with the labels that each got.

#4114 Component.events to define event handlers ensured to be attached/detached on lifecycle (#4025)
  docs/core/component.md
  src/core/component.js
  tests/core/component.test.js
Labels: needs review

#4116 Update gamepads list on every tick for Chrome browsers (fix #4099)
  src/systems/tracked-controls-webvr.js
Labels: needs review

#4016 Remove extra properties from objectPool objects
  src/core/component.js
  src/utils/object-pool.js
Labels: needs changes

#4047 invert the index values assumed for left and right vive controllers
  src/components/vive-controls.js
Labels: needs answers / feedback

#4082 if el is undefined on remove child entity, call removeFromParent
  src/core/a-entity.js
  tests/core/a-entity.test.js
Labels: needs answers / feedback

#4121 keep components attached to entity if whole entity is detached (fixes #4027)
  docs/core/entity.md
  src/core/a-entity.js
  src/core/component.js
  tests/components/geometry.test.js
  tests/core/a-entity.test.js
Labels: needs review

#4122 throw error message for invalid property path for animations (fixes #4105)
  examples/animation/arms/index.html
  src/components/animation.js
Labels: needs review

#4140 fix Entity.destroy attached check
  src/core/a-entity.js
  tests/core/a-entity.test.js
Labels: needs review

#4143 Verify fullscreenElement before exiting fullscreen. Chrome m71+ returns error withouth this check (fix #4136)
  src/core/scene/a-scene.js
Labels: needs review

#4146 Metatag to hide URL bar in iOS when entering fullscreen mode
  src/core/scene/metaTags.js
Labels: needs review
