Repository aframevr/aframe, pull requests merged in 2019-02, with the labels that each got.

#3989 Add precission property to renderer component
  docs/components/renderer.md
  docs/introduction/faq.md
  src/core/scene/a-scene.js
  src/systems/renderer.js
Labels: needs changes

#3987 Move THREE dependency to supermedium THREE fork hosted in npm (fix #3781)
  package.json
  src/lib/three.js
Labels: needs changes

#3995 Honor camera position when entering fullscreen (fix #3902)
  src/components/look-controls.js
Labels: needs review

#3998 Disable/Renable VR before taking screenshot. Don't make equirectangular quad children of the scene camera (fix #3337, fix #3727)
  src/components/scene/screenshot.js
Labels: needs review

#4000 Always emit cursor click events if mouse based cursor enabled
  src/components/cursor.js
  tests/components/cursor.test.js
Labels: needs review

#3967 highRefreshRate property to enable 72hz mode on Oculus Browser (fix #3943)
  docs/components/renderer.md
  src/core/scene/a-scene.js
  src/systems/renderer.js
  tests/systems/renderer.test.js
Labels: needs review

#4005 fix single selector property type
  src/core/component.js
  tests/components/sound.test.js
  tests/core/component.test.js
Labels: needs review

#4021 Add repl.it link
  README.md
Labels: needs review

#4022 Consider case when both WebVR and WebXR are available
  src/core/scene/a-scene.js
  src/core/scene/loadingScreen.js
Labels: needs review

#4024 Use index to detect vive controlles since handennnes is not always ailable and determined at runtime (fix #4013)
  src/components/vive-controls.js
Labels: needs review

#3932 Migrate hand model to glTF. Old JSONLoader has been deprecated from latest THREE
  examples/showcase/link-traversal/city.html
  examples/showcase/link-traversal/index.html
  examples/showcase/link-traversal/js/components/ground.js
  examples/showcase/link-traversal/mountains.html
  examples/showcase/link-traversal/sunrise.html
  examples/showcase/tracked-controls/vendor/LegacyJSONLoader.js
  src/components/hand-controls.js
Labels: needs review

#4028 bump animejs to one with memory/garbage reduction patches
  examples/animation/aframe-logo/index.html
  examples/showcase/anime-UI/index.html
  package.json
  src/components/animation.js
  tests/node/test.js
Labels: needs tests fixed

#4030 handle null device from xr.getDevice
  src/utils/device.js
Labels: needs review

#4033 Replace isOculusGo with isMobileVR function (fix #4032)
  src/utils/device.js
  src/utils/index.js
Labels: needs review

#4037 Handle navigator.xr.requestDevice promise error (fix #4035)
  src/utils/device.js
Labels: needs review
