Repository aframevr/aframe, pull requests merged in 2019-08, with the labels that each got.

#4250 fix component.events singleton, events being overridden by components of the same type
  src/core/component.js
  tests/core/component.test.js
Labels: needs review

#4249 only emit cursor mouseup if mousedown originated on scene
  src/components/cursor.js
  tests/components/cursor.test.js
Labels: needs changes

#4240 Set 72Hz mode by default on Oculus Browser (fix #4232)
  src/systems/renderer.js
  src/utils/device.js
Labels: needs review

#4246 Fixes #3592: Fix resolution drop on exiting VR mode
  src/core/scene/a-scene.js
  tests/__init.test.js
  tests/core/scene/a-scene.test.js
Labels: needs tests fixed
