Repository aframevr/aframe, pull requests merged in 2020-02, with the labels that each got.

#4433 Material dithering
  docs/components/material.md
  src/components/material.js
Labels: needs changes

#4409 Listens to WebXR selectstart / selectstart and reemits as mousedown / mouseup
  src/components/cursor.js
Labels: work in progress

#4495 use new WebGLRenderer.outputEncoding
  src/systems/renderer.js
  tests/systems/renderer.test.js
Labels: needs tests fixed
